const projects = [
  {
    id: "1",
    name: "Forumium",
    thumbnail: "/projectThumbnail/Forumium.png",
    tools: "React, Tailwind, React Query, Supabase",
    description: "Lorem Ispum",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
  {
    id: "2",
    name: "Fast Pizza",
    thumbnail: "/projectThumbnail/Fastpizza.png",
    tools: "React, Tailwind, Redux",
    description: "Ipsum Lorem",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
  {
    id: "3",
    name: "NexusHealth",
    thumbnail: "/projectThumbnail/Nexus.png",
    tools: "HTML, CSS, JavaScript, Bootstrap, PHP, MYSQL",
    description: "Ipsum Lorem",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
  {
    id: "4",
    name: "Forumium 0.1",
    thumbnail: "/projectThumbnail/Forumium0.1.png",
    tools: "HTML, CSS, JavsScript, Bootstrap, PHP, MYSQL",
    description: "Ipsum Lorem",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
  {
    id: "5",
    name: "NextSteps",
    thumbnail: "/projectThumbnail/NextSteps.png",
    tools: "HTML, CSS, JavaScript, Bootstrap, PHP, MYSQL",
    description: "Ipsum Lorem",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
  {
    id: "6",
    name: "Web Authentication",
    thumbnail: "/projectThumbnail/WebAuth.png",
    tools: "HTML, Bootstrap, PHP, MYSQL",
    description: "Ipsum Lorem",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
  {
    id: "7",
    name: "Fast Pizza",
    thumbnail: "/dummy",
    description: "Ipsum Lorem",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
  {
    id: "8",
    name: "Fast Pizza",
    thumbnail: "/dummy",
    description: "Ipsum Lorem",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
  {
    id: "9",
    name: "Fast Pizza",
    thumbnail: "/dummy",
    description: "Ipsum Lorem",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
  {
    id: "10",
    name: "Fast Pizza",
    thumbnail: "/dummy",
    description: "Ipsum Lorem",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
  {
    id: "11",
    name: "Fast Pizza",
    thumbnail: "/dummy",
    description: "Ipsum Lorem",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
  {
    id: "12",
    name: "Fast Pizza",
    thumbnail: "/dummy",
    description: "Ipsum Lorem",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
  {
    id: "13",
    name: "Fast Pizza",
    thumbnail: "/dummy",
    description: "Ipsum Lorem",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
  {
    id: "14",
    name: "Fast Pizza",
    thumbnail: "/dummy",
    description: "Ipsum Lorem",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
];

export default projects;
