const projects = [
  {
    name: "Forumium",
    thumbnail: "/dummy",
    description: "Lorem Ispum",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
  {
    name: "Fast Pizza",
    thumbnail: "/dummy",
    description: "Ipsum Lorem",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
  {
    name: "Fast Pizza",
    thumbnail: "/dummy",
    description: "Ipsum Lorem",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
  {
    name: "Fast Pizza",
    thumbnail: "/dummy",
    description: "Ipsum Lorem",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
  {
    name: "Fast Pizza",
    thumbnail: "/dummy",
    description: "Ipsum Lorem",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
  {
    name: "Fast Pizza",
    thumbnail: "/dummy",
    description: "Ipsum Lorem",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
  {
    name: "Fast Pizza",
    thumbnail: "/dummy",
    description: "Ipsum Lorem",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
  {
    name: "Fast Pizza",
    thumbnail: "/dummy",
    description: "Ipsum Lorem",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
  {
    name: "Fast Pizza",
    thumbnail: "/dummy",
    description: "Ipsum Lorem",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
  {
    name: "Fast Pizza",
    thumbnail: "/dummy",
    description: "Ipsum Lorem",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
  {
    name: "Fast Pizza",
    thumbnail: "/dummy",
    description: "Ipsum Lorem",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
  {
    name: "Fast Pizza",
    thumbnail: "/dummy",
    description: "Ipsum Lorem",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
  {
    name: "Fast Pizza",
    thumbnail: "/dummy",
    description: "Ipsum Lorem",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
  {
    name: "Fast Pizza",
    thumbnail: "/dummy",
    description: "Ipsum Lorem",
    github: "link",
    live: "link",
    screenshots: "imgPath",
  },
];

export default projects;
